### ISSUE TITLE
Latest docker running on unraid No such file or directory SickBeard.py

### ISSUE THREAD

**Issue by jwshive** [linuxserver/docker-sickchill#24]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Upon starting the docker container, SickChill webpage will render.

This is the last version that worked properly for me.
linuxserver/sickchill:v2020.08.07-1-ls41

## Current Behavior
No page renders, errors spam every second to the log.

## Steps to Reproduce

1. Update docker container to latest
2. Start Docker Container

## Environment
**OS: Unraid 6.8.3**      
**CPU architecture: x86_64** x86_64/arm32/arm64      
**How docker service was installed:**      
Using the menu that comes with the Unraid management UI

## Command used to create docker container (run/create/compose/screenshot)
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='sickchill' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'PGID'='100' -e 'PUID'='99' -p '8083:8081/tcp' -v '/mnt/user/downloads/':'/downloads':'rw' -v '/mnt/user/tv/':'/tv':'rw' -v '/mnt/user/backup/':'/backup':'rw' -v '/mnt/user/appdata/sickchill':'/config':'rw' 'linuxserver/sickchill' 

32304360431aa788283dbf612cca8b23287e4d13937508724bdd07ee3f62d9bc

Looking inside the container, that file does not exist.

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
Setting permissions
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
python: can't open file '/app/sickchill/SickBeard.py': [Errno 2] No such file or directory
...
python: can't open file '/app/sickchill/SickBeard.py': [Errno 2] No such file or directory
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting
```

**Comment by aptalca** [comment]
See #22

**Comment by jwshive** [comment]
I even looked at that but totally missed the very top. Sorry about that.

**Comment by aptalca** [comment]
No worries, that would be great if you could test that build referenced there

**Comment by jwshive** [comment]
I have and it's running fine. Logs just show this, but doesn't impact functionality.
```
2020-09-06 07:36:07 ERROR :: WEBSERVER-HOME_0 :: Could not open static file '/usr/lib/python3.8/site-packages/sickchill/gui/slick/images/network/stargate command.png'
```
