### ISSUE TITLE
ModuleNotFoundError: No module named 'imdb'

### ISSUE THREAD

**Issue by JustinAiken** [linuxserver/docker-sickchill#25]
## Expected Behavior
Sickchill should start up

## Current Behavior
Sickchill does not start up:

```
/usr/lib/python3.8/site-packages/sickchill/locale
/usr/lib/python3.8/site-packages/sickchill/locale
Traceback (most recent call last):
File "/usr/bin/SickChill.py", line 14, in <module>
import sickchill.start
File "/usr/lib/python3.8/site-packages/sickchill/__init__.py", line 1, in <module>
from .show.indexers import indexer, ShowIndexer
File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>
from .handler import ShowIndexer
File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/handler.py", line 5, in <module>
from sickchill.tv import Show, TVEpisode
File "/usr/lib/python3.8/site-packages/sickchill/tv.py", line 15, in <module>
import imdb
ModuleNotFoundError: No module named 'imdb'
```

## Steps to Reproduce
`docker pull linuxserver/sickchill:latest` (which is `linuxserver/sickchill:amd64-2020.9.16.post2-ls43` I believe)

Fixed by reverting to
`linuxserver/sickchill:amd64-2020.9.13.post1-ls42`

## Environment
**OS:**  Unraid 6.8.3     
**CPU architecture:** x86_64      

## Command used to create docker container (run/create/compose/screenshot)

```bash
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d \
  --name='sickchill' \
  --net='bridge'  \
  -e TZ="America/Denver" \
  -e HOST_OS="Unraid" \
  -e 'PGID'='100' -e 'PUID'='99' \
  -p '8081:8081/tcp' \
  -v <volume mounts> \
  'linuxserver/sickchill:latest' 
```

**Comment by XanderStrike** [comment]
**The tag 2020.9.13.post1-ls42 works fine, so this is a recent change**

Question, do these pipelines that update config do any smoke testing? This image has failed to upgrade cleanly twice in the last couple weeks, a small smoke test just to make sure the container accepts http connections on the exposed port would have prevented both this and #22 from going to live in a broken state. I'm happy to help contribute that if you can point me to the pipelines.

**Comment by aptalca** [comment]
This is most likely an upstream issue as we just use their pip package, which is supposed to install all their required dependencies

**Comment by aptalca** [comment]
> **The tag 2020.9.13.post1-ls42 works fine, so this is a recent change**
> 
> Question, do these pipelines that update config do any smoke testing? This image has failed to upgrade cleanly twice in the last couple weeks, a small smoke test just to make sure the container accepts http connections on the exposed port would have prevented both this and #22 from going to live in a broken state. I'm happy to help contribute that if you can point me to the pipelines.

There is a test that spins it up, takes a log and a screenshot and post it here: https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/sickchill/latest/index.html, but it only checks if the docker services are started, in other words checks that our container is starting. If the app is not starting due to upstream issues, we don't currently catch it. It is also not reliable to check the service status because the arm arches are tested via qemu and many images don't work under qemu properly. If we failed the builds, there would be a lot of false negatives.

In any case, here is the ci overview:
https://github.com/linuxserver/pipeline-triggers
https://blog.linuxserver.io/2019/02/21/the-lsio-pipeline-project/

**Comment by aptalca** [comment]
I'm assuming this will be fixed upstream in the next release: https://github.com/SickChill/SickChill/issues/6755#issuecomment-693532903

**Comment by nopoz** [comment]
I've posted a temporary workaround in https://github.com/SickChill/SickChill/issues/6755#issuecomment-693734003
