### ISSUE TITLE
Linuxserver/sickchill broken after last update

### ISSUE THREAD

**Issue by Guesch** [linuxserver/docker-sickchill#31]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
For the app to work after the latest update! :)

## Current Behavior
Docker starts but 404 error while trying to open the webui

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:Unraid
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
Official docker through CA

## Command used to create docker container (run/create/compose/screenshot)
![image](https://user-images.githubusercontent.com/61683661/113685518-a2907800-96c6-11eb-83c5-d87676077780.png)

## Docker logs
Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
SickChill: https://www.patreon.com/SickChill

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
ln: failed to create symbolic link '/app/sickchill/sickchill': File exists

Setting permissions
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
File "/usr/bin/SickChill.py", line 5, in <module>
from SickChill.SickChill import start
File "/usr/bin/SickChill.py", line 5, in <module>
from SickChill.SickChill import start
ModuleNotFoundError: No module named 'SickChill.SickChill'; 'SickChill' is not a package

**Comment by rantanlan** [comment]
just got here to report the same, currenty image seems broken. reverting back to the prior one is working.

**Comment by aptalca** [comment]
Seems to be an upstream issue: https://github.com/SickChill/SickChill/issues/7074

**Comment by mvdpoel** [comment]
Same here indeed
`ModuleNotFoundError: No module named 'SickChill.SickChill'; 'SickChill' is not a package
Traceback (most recent call last):
  File "/usr/bin/SickChill.py", line 5, in <module>
    from SickChill.SickChill import start
  File "/usr/bin/SickChill.py", line 5, in <module>
    from SickChill.SickChill import start
`

**Comment by aptalca** [comment]
Fixed in latest build
