### ISSUE TITLE
Can't open file '/usr/bin/SickChill.py'

### ISSUE THREAD

**Issue by GreatMaker** [linuxserver/docker-sickchill#34]
Just updated, sickchill fails to start looking for /usr/bin/SichChill.py; that is not present in that path.

Tried to re-download the image and delete the container, but same behaviour occours.

[_sickchill_logs (1).txt](https://github.com/linuxserver/docker-sickchill/files/7561057/_sickchill_logs.1.txt)

**Comment by Roxedus** [comment]
Please use the issue template, that way i wouldnt have to ask you of this is regarding the develop branch or not

**Comment by noaho** [comment]
I have the same issue on the normal (unspecified) branch

**Comment by comprofix** [comment]
OS: Linux docker 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
Docker: Docker version 20.10.5+dfsg1, build 55c4c88
Hardware: Dell R720 VM. 
Hypervisor: Proxmox VE 7.1
Container logs - https://www.toptal.com/developers/hastebin/wogiloreki.yaml
Issue: Sickchill not starting. Website shows 502 Bad Gateway. Logs showing 

`python3: can't open file '/usr/bin/SickChill.py': [Errno 2] No such file or directory`

**Comment by comprofix** [comment]
As a temporary solution you need to roll back to previous version. Update your compose file or command and use tag 2021.7.23.

So image should be `ghcr.io/linuxserver/sickchill:2021.7.23`

**Comment by zryk** [comment]
I have the same issue, on the normal unspecified branch - Using this image: linuxserver/sickchill:2021.11.10-ls79

I have rolled back to linuxserver/sickchill:2021.7.23-1-ls78 so the service is still running

**Comment by gielie** [comment]
Same issue here on a synology docker system. 
can someone help me how to rollback on a synology? Or should I wait for an update?

**Comment by j0nnymoe** [comment]
You just need to specify the image mentioned above with whichever way you deploy your containers.

**Comment by bavanl** [comment]
> 
> 
> Same issue here on a synology docker system. can someone help me how to rollback on a synology? Or should I wait for an update?

1.export settings from your current docker  (settings-> export)  and stop this container
2.open de json file and change the "image" name to "linuxserver/sickchill:version-2021.7.23-1" ( make sure you first downloaded this under images).
3. save json and import json as different container/name ( settings -> import)
4.  start this new container and done

when the issue is fixed you can download latest again and stop this temporary container and start your initial container again.

**Comment by jakeman2048** [comment]
I've confirmed this is on the **latest** docker tag. Please remove the "invalid" tags.

It seems the SickChill package is now located at /usr/bin/SickChill not at /usr/bin/SickChill.py. The service file needs to reflect that.

**Comment by gielie** [comment]
> > Same issue here on a synology docker system. can someone help me how to rollback on a synology? Or should I wait for an update?
> 
> 1.export settings from your current docker (settings-> export) and stop this container 2.open de json file and change the "image" name to "linuxserver/sickchill:version-2021.7.23-1" ( make sure you first downloaded this under images). 3. save json and import json as different container/name ( settings -> import) 4. start this new container and done
> 
> when the issue is fixed you can download latest again and stop this temporary container and start your initial container again.

~~Which json file do I need to alter and where can I find this?~~
off course, the json I just exported, tnks, all is working now.

**Comment by ocalvo** [comment]
Seeing the same issue.
Is there a workaround?

**Comment by j0nnymoe** [comment]
@ocalvo as mentioned already, roll back to the previous image.

**Comment by Guesch** [comment]
Quick comment to confirm the issue on the master branch and to kindly ask the dev to remove the "invalid" label from this report!

**Comment by j0nnymoe** [comment]
Done, but for what it's worth. The invalid label is because the OP ignored the issue template we ask to be filled out on opening an issue :) .

**Comment by ghost** [comment]
The package console_script has been renamed from SickChill.py to SickChill.
https://github.com/SickChill/SickChill/commit/725a9fe5c7e3886ae9ccd1fde1caabfbb0978406#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711


Docker image builds and starts with this modification on [root/etc/services.d/sickchill/run](../blob/master/root/etc/services.d/sickchill/run)

```bash 
diff --git a/root/etc/services.d/sickchill/run b/root/etc/services.d/sickchill/run
index d0909b5..370e129 100644
--- a/root/etc/services.d/sickchill/run
+++ b/root/etc/services.d/sickchill/run
@@ -1,5 +1,5 @@
 #!/usr/bin/with-contenv bash

 exec \
-    s6-setuidgid abc python3 /usr/bin/SickChill.py \
+    s6-setuidgid abc python3 /usr/bin/SickChill \
     --datadir /config
```

This file is now a real python entry point rather than a copy of /usr/lib/python3.8/site-packages/SickChill.py

```bash
docker run -it --rm --entrypoint /bin/sh linuxserver/sickchill
root@bf0682d67425:/# cat /usr/bin/SickChill
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from SickChill import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

```bash
docker run -it --rm --entrypoint /bin/sh linuxserver/sickchill:2021.7.23
root@2caa7df66028:/# cat /usr/bin/SickChill.py
#!/usr/bin/env python3

import datetime
import os
import platform
import shutil
import signal
import subprocess
import sys
import threading
import time
import traceback

import sickchill.start
from sickchill import logger, settings
from sickchill.init_helpers import check_installed, remove_pid_file, setup_gettext
from sickchill.movies import MovieList

...
...
...

if __name__ == "__main__":
    # start SickChill
    SickChill().start()
    remove_pid_file()
```

**Comment by jakeman2048** [comment]
> Done, but for what it's worth. The invalid label is because the OP ignored the issue template we ask to be filled out on opening an issue :) .

Not worth anything. jk <3

This issue is so fatal that it's self-evident to anyone who actually ran this release. The issue templates should only be necessary to help re-create the problem on your end. If this problem somehow _doesn't_ occur for someone, I believe that is more needing of the issue template.
