### ISSUE TITLE
AttributeError: module 'requests.exceptions' has no attribute 'InvalidJSONError'

### ISSUE THREAD

**Issue by Ulrar** [linuxserver/docker-sickchill#36]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
Sickchill should start

## Current Behavior
It doesn't

## Steps to Reproduce
Update sickchill to the latest image version

## Environment
**OS:** Unraid (Linux)
**CPU architecture:** x86_64
**How docker service was installed:** Unraid

## Command used to create docker container (run/create/compose/screenshot)
Using the linuxserver template in the Unraid community apps

## Docker logs
```
Checking poetry
sickchill installed: True
Traceback (most recent call last):
  File "/usr/bin/SickChill", line 5, in <module>
    from SickChill import main
  File "/usr/lib/python3.8/site-packages/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/usr/lib/python3.8/site-packages/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/usr/lib/python3.8/site-packages/sickchill/tv.py", line 19, in <module>
    import sickchill.oldbeard.providers
  File "/usr/lib/python3.8/site-packages/sickchill/oldbeard/providers/__init__.py", line 4, in <module>
    import sickchill.oldbeard.helpers
  File "/usr/lib/python3.8/site-packages/sickchill/oldbeard/helpers.py", line 1315, in <module>
    requests.exceptions.InvalidJSONError,
AttributeError: module 'requests.exceptions' has no attribute 'InvalidJSONError'
```

Also see the related issue on the sickchill repo, looks like it's affecting more than just linuxserver so it might be a dependency issue or something like that : https://github.com/SickChill/SickChill/issues/7866

**Comment by steffenlongva** [comment]
it can be tmp fixed by running these within the container and restarting
```
pip3 install importlib.metadata
pip3 install --upgrade requests 
```

**Comment by Ulrar** [comment]
Correct, sorry I forgot to update here but yes, installing importlib.metadata which is now required and updating requests to the latest version (2.27) fixes the issue for now.
Let's hope the real problem can be fixed in sickchill's repo to make the next image work out of the box.

**Comment by LapinFou** [comment]
> it can be tmp fixed by running these within the container and restarting
> 
> ```
> pip3 install importlib.metadata
> pip3 install --upgrade requests 
> ```

Same issue with Docker running on a Synology NAS.
This trick did solve the problem! 😍
Thanks.

**Comment by Ulrar** [comment]
Latest does seem to work fine, thanks

**Comment by LapinFou** [comment]
I checked on Synology NAS.
Latest does also work fine.
Thanks for this quick fix. 👍😊
