### ISSUE TITLE
Latest version (2022.7.20-ls99) is not starting

### ISSUE THREAD

**Issue by bengtfredh** [linuxserver/docker-sickchill#41]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior

Container not starting:
```sh
sickchill installed: True
/usr/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.7) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/SickChill", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 345, in main
    SickChill().start()
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 90, in start
    settings.DATA_DIR = choose_data_dir(settings.PROG_DIR)
  File "/usr/lib/python3.9/site-packages/sickchill/helper/common.py", line 404, in choose_data_dir
    if location.joinpath(check).exists():
  File "/usr/lib/python3.9/pathlib.py", line 1424, in exists
    self.stat()
  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/sickchill/sickbeard.db'
Checking poetry
sickchill installed: True
```

Change to tag 2022.2.20-ls98 and it is running.

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by steffenlongva** [comment]
Anyone know a 'temp fix' for this? 👀

**Comment by ZeBadger** [comment]
Same issue.  I modified by docker-compose.yaml  file to have the old version
   ` image: linuxserver/sickchill:2022.2.20`
and then ran
    `docker-compose up -d`
to rebuild it.  Which fixed the issue.

Broken: 
```
root@server2:~/docker/sickchill# cat docker-compose.yaml
---
version: "2.1"
services:
  sickchill:
    image: linuxserver/sickchill:latest
    container_name: sickchill
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /docker/sickchill/config:/config
      - /docker/sickchill/downloads:/downloads
      - /docker/sickchill/tv:/tv
    ports:
      - 8081:8081
    restart: unless-stopped

```

Fixed:

```
root@server2:~/docker/sickchill# cat docker-compose.yaml
---
version: "2.1"
services:
  sickchill:
    image: linuxserver/sickchill:2022.2.20
    container_name: sickchill
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /docker/sickchill/config:/config
      - /docker/sickchill/downloads:/downloads
      - /docker/sickchill/tv:/tv
    ports:
      - 8081:8081
    restart: unless-stopped

```

**Comment by ihomeautomate** [comment]
Confirming [2022.7.20-ls99](https://github.com/linuxserver/docker-sickchill/releases/tag/2022.7.20-ls99) is broken indeed. Container doesn't start, but log keeps spamming the mentioned error.
Reverting back to [2022.2.20-ls98](https://github.com/linuxserver/docker-sickchill/releases/tag/2022.2.20-ls98) in the mean time.

**Comment by LapinFou** [comment]
Same problem and same error for my Synology DS916+.

I rollback to [2022.2.20](https://hub.docker.com/layers/sickchill/linuxserver/sickchill/2022.2.20/images/sha256-d1242bc02d9dca9f18e1bb1c8458ba4755fcc5505515a6c1b275d945ed46eb04?context=explore).
This did fixed the problem for now.

**Comment by Ulrar** [comment]
Looks like it's trying to start in /root instead of /config, even with the datadir argument being correctly passed

**Comment by gielie** [comment]
> Same problem and same error for my Synology DS916+.
> 
> I rollback to [2022.2.20](https://hub.docker.com/layers/sickchill/linuxserver/sickchill/2022.2.20/images/sha256-d1242bc02d9dca9f18e1bb1c8458ba4755fcc5505515a6c1b275d945ed46eb04?context=explore). This did fixed the problem for now.

how do I revert back to a previous version in Synology docker?

**Comment by LapinFou** [comment]
> > Same problem and same error for my Synology DS916+.
> > I rollback to [2022.2.20](https://hub.docker.com/layers/sickchill/linuxserver/sickchill/2022.2.20/images/sha256-d1242bc02d9dca9f18e1bb1c8458ba4755fcc5505515a6c1b275d945ed46eb04?context=explore). This did fixed the problem for now.
> 
> how do I revert back to a previous version in Synology docker?

I'm using [Portainer](https://www.portainer.io/) to manage my containers (a lot more flexible).

If your are using the default Syno GUI, you must go in the "Image" tab, then Add from an URL:
`https://registry.hub.docker.com/r/linuxserver/sickchill`
When the identification menu pops-up, you must scroll down and select the version **2022.2.20**.
Finally you must stop then rebuild you container with this image version.
I don't know the exact procedure, but I'm sure you got the idea. 😉

**Comment by steffenlongva** [comment]
for unraid i just added the tag to the repository field; linuxserver/sickchill:2022.2.20

**Comment by gnoumph** [comment]
Hello!  
Same issue here, reverting back to [`2022.2.20`](https://github.com/linuxserver/docker-sickchill/releases/tag/2022.2.20-ls98) for now.

**Comment by ghost** [comment]
Hello, 
There's a new check in SickChill on home directory path to find configuration files.
https://github.com/SickChill/SickChill/blob/d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5/sickchill/helper/common.py#L400

This breaks service start from **/etc/services.d/sickchill/run**  because HOME gets resolved to /root, and there is a permission issue which triggers an exception in python.

Adding `export HOME=/config` in **/etc/services.d/sickchill/run** after running scripts in /etc/cont-init.d fixes the service start

> root@7b4fc0d13124:/etc/cont-init.d# bash -x /etc/services.d/sickchill/run
> + export HOME=/config
> + HOME=/config
> + exec s6-setuidgid abc python3 /usr/bin/SickChill --datadir /config
> Checking poetry
> sickchill installed: True
> /usr/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.7) doesn't match a supported version!
>   warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
> sickchill installed: True
> 2022-07-24 11:35:57 INFO :: MAIN :: Starting SickChill [pip] using '/config/config.ini'
> 2022-07-24 11:35:57 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
> 2022-07-24 11:35:57 INFO :: CHECKVERSION :: Checking for updates using PIP

**Comment by Ulrar** [comment]
@pigsyn thanks, can confirm adding HOME=/config to the containers env fixes it

**Comment by XanderStrike** [comment]
I'm still getting this issue on the [latest image](https://hub.docker.com/layers/linuxserver/sickchill/latest/images/sha256-b966729f3177f3371ac3b890ac00ddc61a2b2da7715ac506f6629b77c540b32f?context=explore) from 3 hours ago. Does something need to change about how I run it?

Edit: Portainer had saved `HOME=/root` so I had to update that to `HOME=/config` and now it works 🎉

**Comment by totalisator** [comment]
how to do this in unraid?

**Comment by Ulrar** [comment]
@totalisator you shouldn't need to, the image is fixed.
But you'd just edit your container, click the add button at the bottom, select variable from the drop down and use 'HOME' for the name and '/config' for the value
