### ISSUE TITLE
SickChill Unable to read unionfs, OMV5, Portainer

### ISSUE THREAD

**Issue by theomajigga** [linuxserver/docker-sickchill#45]
Can view fs in docker console, shows all folders. Open same directory in SickChill web GUI, shows no shows or files. 

## Expected Behavior
Clicking on TV Shows, Add Existing Shows, and adding directory should show all shows saved in directory

## Current Behavior
Nothing showed in directory. 

## Steps to Reproduce
1. Latest Image pull
2. Add TV Show, add existing Show, Browse
3. No shows listed

## Environment
**OS: OMV5
**CPU architecture:** pi4
**How docker service was installed:**
using portainer pull

**Comment by j0nnymoe** [comment]
This will be a permissions issue that the user you're running the container as is unable to read those folders. If you've tested by entering the container without specifying user abc then it'll be root user and that will always work.

**Comment by theomajigga** [comment]
ok, I'll try a different user... What is the default user?

**Comment by theomajigga** [comment]
You are correct, how can I fix the issue? Run container as root :|

**Comment by j0nnymoe** [comment]
You run it as a non root users on your host. I don't know the specifics for omv.

**Comment by theomajigga** [comment]
Fixed by setting 
PUID 1000
GUID 100
