### ISSUE TITLE
[BUG] SickChill fails to start after update to the latest version

### ISSUE THREAD

**Issue by MagicalCrib** [linuxserver/docker-sickchill#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After update to the latest version, SickChill fails to start due to missing cachecontrol pachage, and also due to updated SQLAlchemy package to the latest version (issue introduced in commit https://github.com/linuxserver/docker-sickchill/commit/e2a658cb9f63f9cc90305d216ef705ab7f95de31).
The following commands fix the problem:
`pip install -U sqlalchemy==1.4.48`
`pip install cachecontrol`

Also, reverting to an old version of urllib, stops HTTPResponse error (SickChill issue https://github.com/SickChill/sickchill/issues/8437)
`pip install -U requests==2.28.2 urllib3==1.26.15`

### Expected Behavior

SickChill to start normally.

### Steps To Reproduce

Update to the latest version and start the container.

### Environment

```markdown
- OS:QNAP running on Intel Celeron CPU
- How docker service was installed: using container station
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=sickchill \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Lisbon \
  -p 8081:8081 \
  -v /path to config:/config \
  -v /path to downloads:/downloads \
  -v /path to TV:/tv \
  --restart always \
  lscr.io/linuxserver/sickchill:latest
```

### Container logs

```bash
Logs lost after workaround and several container restarts
```

**Comment by j0nnymoe** [comment]
You should not be running the update within the container but update the image itself.

As you can see here: https://ci-tests.linuxserver.io/linuxserver/sickchill/latest/index.html our latest image does boot fine.

**Comment by MagicalCrib** [comment]
You are right, I deleted the container and created it again and it boots properly.
I'm using watchtower to update my containers, it did an update during the night which broke the container, I then forced a new update and it was still broken. Not sure what went wrong...
