### ISSUE TITLE
2023.6.27-ls146 upgrade broken?

### ISSUE THREAD

**Issue by justinmaiuto** [linuxserver/docker-sickchill#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sickchill does not start up. Seems to be an symlink issue with Python

![image](https://github.com/linuxserver/docker-sickchill/assets/8307789/8beb6e59-3cf0-40f2-8136-037ab7215901)

### Expected Behavior

Sickchill should start as expected.

### Steps To Reproduce

1. Upgrade to 2023.6.27-ls146
2. Start container

### Environment

```markdown
- OS:
- How docker service was installed: Synology container manager
```

### CPU architecture

x86-64

### Docker creation

```bash
Synology container manager
```

### Container logs

```bash
linuxserver-sickchill1				
date	stream	content		
14/07/2023 10:25	stdout	ModuleNotFoundError: No module named 'SickChill'		
				
14/07/2023 10:25	stdout	    from SickChill import main		
				
14/07/2023 10:25	stdout	  File \/lsiopy/bin/SickChill\"	 line 5	 in <module>
```

**Comment by Roxedus** [comment]
Take a look at https://info.linuxserver.io/issues/2023-05-22-portainer/
